name: Generate Logos

on:
  push:
    branches: [ main ]
    paths:
      - 'identities.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Generate
      working-directory: scripts/logo-generate
      env:
        OUTPUT_PATH: ${{ env.GITHUB_WORKSPACE }}/assets/logos
        IDENTITIES_PATH: ${{ env.GITHUB_WORKSPACE }}/identities.yml
      run: |
        npm ci
        node index
    - name: Commit Logos
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: 'chore: update logos [skip ci]'
        file_pattern: assets/logos/*.svg
